name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          TOKEN: ${{ secrets.TOKEN }}
          signing_key: ${{ secrets.SIGNING_KEY }}
          signingKeyBase64: ${{ secrets.SIGNING_KEY2 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

        run: |
          echo $TOKEN | xxd -ps
          echo $signing_key | xxd -ps
          echo $signingKeyBase64 | xxd -ps
          echo $alias | xxd -ps
          echo $keyStorePassword | xxd -ps
          echo $keyPassword | xxd -ps